//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accesos
    {
        public long id { get; set; }
        public long FORMULARIOS_id { get; set; }
        public long PERMISOS_id { get; set; }
        public long ROL_id { get; set; }
    
        public virtual formularios formularios { get; set; }
        public virtual permisos permisos { get; set; }
        public virtual rol rol { get; set; }
    }
}
