//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accesos
    {
        public long id { get; set; }
        public long FORMULARIOS_id { get; set; }
        public long PERMISOS_id { get; set; }
        public long ROL_id { get; set; }
    
        public virtual formularios formularios { get; set; }
        public virtual permisos permisos { get; set; }
        public virtual rol rol { get; set; }
    }
}
