//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gasiswEntities : DbContext
    {
        public gasiswEntities()
            : base("name=gasiswEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<caja> caja { get; set; }
        public DbSet<categoria_producto> categoria_producto { get; set; }
        public DbSet<cliente> cliente { get; set; }
        public DbSet<d_compra> d_compra { get; set; }
        public DbSet<d_orden_compra> d_orden_compra { get; set; }
        public DbSet<d_venta> d_venta { get; set; }
        public DbSet<departamento> departamento { get; set; }
        public DbSet<empleado> empleado { get; set; }
        public DbSet<facturacion> facturacion { get; set; }
        public DbSet<formularios> formularios { get; set; }
        public DbSet<historial_caja> historial_caja { get; set; }
        public DbSet<inventario> inventario { get; set; }
        public DbSet<kardex> kardex { get; set; }
        public DbSet<lote> lote { get; set; }
        public DbSet<m_compra> m_compra { get; set; }
        public DbSet<m_orden_compra> m_orden_compra { get; set; }
        public DbSet<m_venta> m_venta { get; set; }
        public DbSet<moviementos_caja> moviementos_caja { get; set; }
        public DbSet<movimiento> movimiento { get; set; }
        public DbSet<municipio> municipio { get; set; }
        public DbSet<nota_credito_compra> nota_credito_compra { get; set; }
        public DbSet<nota_credito_venta> nota_credito_venta { get; set; }
        public DbSet<permisos> permisos { get; set; }
        public DbSet<presentacion_producto> presentacion_producto { get; set; }
        public DbSet<proveedor> proveedor { get; set; }
        public DbSet<rol> rol { get; set; }
        public DbSet<seccion_bodega> seccion_bodega { get; set; }
        public DbSet<sucursal> sucursal { get; set; }
        public DbSet<tipo_compra> tipo_compra { get; set; }
        public DbSet<tipo_documento> tipo_documento { get; set; }
        public DbSet<tipo_facturacion> tipo_facturacion { get; set; }
        public DbSet<tipo_movimiento> tipo_movimiento { get; set; }
        public DbSet<usuario> usuario { get; set; }
        public DbSet<accesos> accesos { get; set; }
        public DbSet<producto> producto { get; set; }
        public DbSet<estacion> estacion { get; set; }
    }
}
