//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.facturacion = new HashSet<facturacion>();
            this.nota_credito_venta = new HashSet<nota_credito_venta>();
        }
    
        public long id { get; set; }
        public string nombre1 { get; set; }
        public string nombre2 { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public long MUNICIPIO_id { get; set; }
        public string num_dui { get; set; }
        public string email { get; set; }
        public string giro { get; set; }
    
        public virtual municipio municipio { get; set; }
        public virtual ICollection<facturacion> facturacion { get; set; }
        public virtual ICollection<nota_credito_venta> nota_credito_venta { get; set; }
    }
}
