//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.facturacion = new HashSet<facturacion>();
            this.nota_credito_venta = new HashSet<nota_credito_venta>();
        }
    
        public long id { get; set; }
        public string nombre1 { get; set; }
        public string nombre2 { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public long MUNICIPIO_id { get; set; }
        public string num_dui { get; set; }
        public string email { get; set; }
    
        public virtual municipio municipio { get; set; }
        public virtual ICollection<facturacion> facturacion { get; set; }
        public virtual ICollection<nota_credito_venta> nota_credito_venta { get; set; }
    }
}
