//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class d_compra
    {
        public long id { get; set; }
        public long M_COMPRA_id { get; set; }
        public long PRODUCTO_id { get; set; }

        [Required]
        public int cantidad_producto { get; set; }

        [Required]
        public float costo_unitario { get; set; }
        public float total { get; set; }
        public virtual m_compra m_compra { get; set; }
        public virtual producto producto { get; set; }
    }
}
