//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_orden_compra
    {
        public long id { get; set; }
        public long M_ORDEN_COMPRA_id { get; set; }
        public long PRODUCTO_id { get; set; }
        public string cantidad { get; set; }
    
        public virtual m_orden_compra m_orden_compra { get; set; }
        public virtual producto producto { get; set; }
    }
}
