//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_venta
    {
        public long id { get; set; }
        public long PRODUCTO_id { get; set; }
        public int cantidad_producto { get; set; }
        public float total { get; set; }
        public long M_VENTA_id { get; set; }
        public float precio_u { get; set; }
    
        public virtual m_venta m_venta { get; set; }
        public virtual producto producto { get; set; }
    }
}
