//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public empleado()
        {
            this.m_compra = new HashSet<m_compra>();
            this.m_venta = new HashSet<m_venta>();
            this.m_orden_compra = new HashSet<m_orden_compra>();
            this.m_orden_compra1 = new HashSet<m_orden_compra>();
            this.usuario = new HashSet<usuario>();
        }
    
        public long id { get; set; }
        public string nombre1 { get; set; }
        public string nombre2 { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public long MUNICIPIO_id { get; set; }
        public long SUCURSAL_id { get; set; }
    
        public virtual municipio municipio { get; set; }
        public virtual sucursal sucursal { get; set; }
        public virtual ICollection<m_compra> m_compra { get; set; }
        public virtual ICollection<m_venta> m_venta { get; set; }
        public virtual ICollection<m_orden_compra> m_orden_compra { get; set; }
        public virtual ICollection<m_orden_compra> m_orden_compra1 { get; set; }
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
