//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturacion
    {
        public long id { get; set; }
        public long TIPO_FACTURACION_id { get; set; }
        public Nullable<long> CLIENTE_id { get; set; }
        public long M_VENTA_id { get; set; }
        public string num_documento { get; set; }
        public Nullable<long> TIPO_DOCUMENTO_id { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual m_venta m_venta { get; set; }
        public virtual tipo_documento tipo_documento { get; set; }
        public virtual tipo_facturacion tipo_facturacion { get; set; }
    }
}
