//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturacion
    {
        public long id { get; set; }
        public long TIPO_FACTURACION_id { get; set; }
        public Nullable<long> CLIENTE_id { get; set; }
        public long M_VENTA_id { get; set; }
        public string num_documento { get; set; }
        public Nullable<long> TIPO_DOCUMENTO_id { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual m_venta m_venta { get; set; }
        public virtual tipo_documento tipo_documento { get; set; }
        public virtual tipo_facturacion tipo_facturacion { get; set; }
    }
}
