//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_caja
    {
        public long id { get; set; }
        public long CAJA_id { get; set; }
        public long MOVIEMENTOS_CAJA_id { get; set; }
        public float total_caja { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual caja caja { get; set; }
        public virtual moviementos_caja moviementos_caja { get; set; }
    }
}
