//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_caja
    {
        public long id { get; set; }
        public long CAJA_id { get; set; }
        public long MOVIEMENTOS_CAJA_id { get; set; }
        public float total_caja { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual caja caja { get; set; }
        public virtual moviementos_caja moviementos_caja { get; set; }
    }
}
