//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kardex
    {
        public kardex()
        {
            this.inventario = new HashSet<inventario>();
        }
    
        public long id { get; set; }
        public int cantidad_producto { get; set; }
        public System.DateTime fecha { get; set; }
        public float precio_u { get; set; }
        public long LOTE_id { get; set; }
        public long SUCURSAL_id { get; set; }
        public int total_producto { get; set; }
        public long MOVIMIENTO_id { get; set; }
    
        public virtual ICollection<inventario> inventario { get; set; }
        public virtual sucursal sucursal { get; set; }
        public virtual lote lote { get; set; }
        public virtual movimiento movimiento { get; set; }
    }
}
