//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lote
    {
        public lote()
        {
            this.kardex = new HashSet<kardex>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
        public long PRODUCTO_id { get; set; }
        public long SECCION_BODEGA_id { get; set; }
    
        public virtual ICollection<kardex> kardex { get; set; }
        public virtual seccion_bodega seccion_bodega { get; set; }
        public virtual producto producto { get; set; }
    }
}
