//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lote
    {
        public lote()
        {
            this.kardex = new HashSet<kardex>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
        public long PRODUCTO_id { get; set; }
        public long SECCION_BODEGA_id { get; set; }
    
        public virtual ICollection<kardex> kardex { get; set; }
        public virtual seccion_bodega seccion_bodega { get; set; }
        public virtual producto producto { get; set; }
    }
}
