//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_compra
    {
        public m_compra()
        {
            this.d_compra = new HashSet<d_compra>();
            this.nota_credito_compra = new HashSet<nota_credito_compra>();
        }
    
        public long id { get; set; }
        public Nullable<System.DateTime> fecha_compra { get; set; }
        public long PROVEEDOR_id { get; set; }
        public float total_compra { get; set; }
        public long EMPLEADO_id { get; set; }
        public long TIPO_COMPRA_id { get; set; }
    
        public virtual ICollection<d_compra> d_compra { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual proveedor proveedor { get; set; }
        public virtual tipo_compra tipo_compra { get; set; }
        public virtual ICollection<nota_credito_compra> nota_credito_compra { get; set; }
    }
}
