//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_orden_compra
    {
        public m_orden_compra()
        {
            this.d_orden_compra = new HashSet<d_orden_compra>();
        }
    
        public long id { get; set; }
        public System.DateTime fecha_emitida { get; set; }
        public long emitido_EMPLEADO_id { get; set; }
        public bool estado { get; set; }
        public Nullable<long> aprobado_EMPLEADO_id { get; set; }
        public long PROVEEDOR_id { get; set; }
    
        public virtual ICollection<d_orden_compra> d_orden_compra { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual empleado empleado1 { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
