//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_venta
    {
        public m_venta()
        {
            this.d_venta = new HashSet<d_venta>();
            this.facturacion = new HashSet<facturacion>();
            this.moviementos_caja = new HashSet<moviementos_caja>();
            this.nota_credito_venta = new HashSet<nota_credito_venta>();
        }
    
        public long id { get; set; }
        public System.DateTime fecha_venta { get; set; }
        public long EMPLEADO_id { get; set; }
        public float total { get; set; }
    
        public virtual ICollection<d_venta> d_venta { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual ICollection<facturacion> facturacion { get; set; }
        public virtual ICollection<moviementos_caja> moviementos_caja { get; set; }
        public virtual ICollection<nota_credito_venta> nota_credito_venta { get; set; }
    }
}
