//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class moviementos_caja
    {
        public moviementos_caja()
        {
            this.historial_caja = new HashSet<historial_caja>();
        }
    
        public long id { get; set; }
        public long CAJA_id { get; set; }
        public System.DateTime fecha { get; set; }
        public float monto { get; set; }
        public long TIPO_MOVIMIENTO_id { get; set; }
        public Nullable<long> M_VENTA_id { get; set; }
    
        public virtual caja caja { get; set; }
        public virtual ICollection<historial_caja> historial_caja { get; set; }
        public virtual m_venta m_venta { get; set; }
        public virtual tipo_movimiento tipo_movimiento { get; set; }
    }
}
