//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class moviementos_caja
    {
        public moviementos_caja()
        {
            this.historial_caja = new HashSet<historial_caja>();
        }
    
        public long id { get; set; }
        public long CAJA_id { get; set; }
        public System.DateTime fecha { get; set; }
        public float monto { get; set; }
        public long TIPO_MOVIMIENTO_id { get; set; }
        public Nullable<long> M_VENTA_id { get; set; }
    
        public virtual caja caja { get; set; }
        public virtual ICollection<historial_caja> historial_caja { get; set; }
        public virtual m_venta m_venta { get; set; }
        public virtual tipo_movimiento tipo_movimiento { get; set; }
    }
}
