//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public producto()
        {
            this.d_compra = new HashSet<d_compra>();
            this.d_orden_compra = new HashSet<d_orden_compra>();
            this.d_venta = new HashSet<d_venta>();
            this.inventario = new HashSet<inventario>();
            this.lote = new HashSet<lote>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
        public long PRESENTACION_PRODUCTO_id { get; set; }
        public long CATEGORIA_PRODUCTO_id { get; set; }
        public float precio_venta_u { get; set; }
        public bool estado { get; set; }
        public long PROVEEDOR_id { get; set; }
    
        public virtual categoria_producto categoria_producto { get; set; }
        public virtual ICollection<d_compra> d_compra { get; set; }
        public virtual ICollection<d_orden_compra> d_orden_compra { get; set; }
        public virtual ICollection<d_venta> d_venta { get; set; }
        public virtual ICollection<inventario> inventario { get; set; }
        public virtual ICollection<lote> lote { get; set; }
        public virtual presentacion_producto presentacion_producto { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
