//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursal
    {
        public sucursal()
        {
            this.caja = new HashSet<caja>();
            this.empleado = new HashSet<empleado>();
            this.kardex = new HashSet<kardex>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
        public long MUNICIPIO_id { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<caja> caja { get; set; }
        public virtual ICollection<empleado> empleado { get; set; }
        public virtual ICollection<kardex> kardex { get; set; }
        public virtual municipio municipio { get; set; }
    }
}
