//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursal
    {
        public sucursal()
        {
            this.caja = new HashSet<caja>();
            this.empleado = new HashSet<empleado>();
            this.kardex = new HashSet<kardex>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
        public long MUNICIPIO_id { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<caja> caja { get; set; }
        public virtual ICollection<empleado> empleado { get; set; }
        public virtual ICollection<kardex> kardex { get; set; }
        public virtual municipio municipio { get; set; }
    }
}
