//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_facturacion
    {
        public tipo_facturacion()
        {
            this.facturacion = new HashSet<facturacion>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<facturacion> facturacion { get; set; }
    }
}
