//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_movimiento
    {
        public tipo_movimiento()
        {
            this.moviementos_caja = new HashSet<moviementos_caja>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<moviementos_caja> moviementos_caja { get; set; }
    }
}
