//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_movimiento
    {
        public tipo_movimiento()
        {
            this.moviementos_caja = new HashSet<moviementos_caja>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<moviementos_caja> moviementos_caja { get; set; }
    }
}
