//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public long id { get; set; }
        public string nombre { get; set; }
        public string password { get; set; }
        public long ROL_id { get; set; }
        public long EMPLEADO_id { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual rol rol { get; set; }
    }
}
